### ISSUE TITLE
설치시 권한 설정에 대해 질문이 있습니다

### ISSUE THREAD

**Issue by chcjswo** [GrotesQ/Codelab-React-Native-4th#2]
강사님 안녕하세요~
이번에 강사님 강의를 들었던 수강생입니다.
덕분에 좋은 강의 잘 들었습니다.
질문이 있습니다.
빌드 실습때 사용했던 simple-chat([https://github.com/GrotesQ/Codelab-React-Native-4th/tree/master/simple-chat](url))을 실제 안드로이드 기계에 설치를 했는데 요구하는 권한이 너무 많은데 권한을 최대한 줄이거나 필요없는 권한은 애초에 사용하지 않게 설정하는 방법이 있을까요?

**Comment by Unk** [comment]
expo는 정교한 수술용 메스라기 보다는 큼직큼직하게 썰어버리는 전기톱 같은 도구라고 볼 수 있습니다.

react-native-cli 를 이용해서 한땀한땀 세팅을 해보시는건 어떨까요 :)
